name: test

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - name: Setup Node
          uses: action/setup-node@v4
          with:
            node-version: '22'
            cache: 'npm'
        - run: npm ci
        - run: npm test














    